# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt5_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(988, 566)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.controller_frame = QtWidgets.QFrame(self.centralwidget)
        self.controller_frame.setGeometry(QtCore.QRect(10, 0, 371, 541))
        self.controller_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controller_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controller_frame.setObjectName("controller_frame")
        self.station_id_label = QtWidgets.QLabel(self.controller_frame)
        self.station_id_label.setGeometry(QtCore.QRect(10, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.station_id_label.setFont(font)
        self.station_id_label.setObjectName("station_id_label")
        self.station_id_line_edit = QtWidgets.QLineEdit(self.controller_frame)
        self.station_id_line_edit.setGeometry(QtCore.QRect(10, 60, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.station_id_line_edit.setFont(font)
        self.station_id_line_edit.setObjectName("station_id_line_edit")
        self.observations_group_box = QtWidgets.QGroupBox(self.controller_frame)
        self.observations_group_box.setGeometry(QtCore.QRect(10, 100, 351, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.observations_group_box.setFont(font)
        self.observations_group_box.setObjectName("observations_group_box")
        self.min_max_temperature_check_box = QtWidgets.QCheckBox(self.observations_group_box)
        self.min_max_temperature_check_box.setGeometry(QtCore.QRect(10, 30, 331, 21))
        self.min_max_temperature_check_box.setChecked(True)
        self.min_max_temperature_check_box.setObjectName("min_max_temperature_check_box")
        self.precipitation_check_box = QtWidgets.QCheckBox(self.observations_group_box)
        self.precipitation_check_box.setGeometry(QtCore.QRect(10, 60, 331, 21))
        self.precipitation_check_box.setChecked(False)
        self.precipitation_check_box.setObjectName("precipitation_check_box")
        self.get_data_push_button = QtWidgets.QPushButton(self.controller_frame)
        self.get_data_push_button.setGeometry(QtCore.QRect(10, 300, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.get_data_push_button.setFont(font)
        self.get_data_push_button.setObjectName("get_data_push_button")
        self.status_text_label = QtWidgets.QLabel(self.controller_frame)
        self.status_text_label.setGeometry(QtCore.QRect(10, 350, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.status_text_label.setFont(font)
        self.status_text_label.setObjectName("status_text_label")
        self.status_value_label = QtWidgets.QLabel(self.controller_frame)
        self.status_value_label.setGeometry(QtCore.QRect(66, 350, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.status_value_label.setFont(font)
        self.status_value_label.setText("")
        self.status_value_label.setObjectName("status_value_label")
        self.diagram_frame = QtWidgets.QFrame(self.centralwidget)
        self.diagram_frame.setGeometry(QtCore.QRect(380, 0, 601, 541))
        self.diagram_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.diagram_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.diagram_frame.setObjectName("diagram_frame")
        main_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.actionkk = QtWidgets.QAction(main_window)
        self.actionkk.setObjectName("actionkk")

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Weather anomaly detection"))
        self.station_id_label.setText(_translate("main_window", "Station ID"))
        self.station_id_line_edit.setText(_translate("main_window", "USC00080228"))
        self.observations_group_box.setTitle(_translate("main_window", "Observations"))
        self.min_max_temperature_check_box.setText(_translate("main_window", "Min / max temperature"))
        self.precipitation_check_box.setText(_translate("main_window", "Precipitation"))
        self.get_data_push_button.setText(_translate("main_window", "Get data"))
        self.status_text_label.setText(_translate("main_window", "Status:"))
        self.actionkk.setText(_translate("main_window", "kk"))
        self.actionkk.setStatusTip(_translate("main_window", "hi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
