# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt5_design_tutorial_resizable.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tutorial_window(object):
    def setupUi(self, tutorial_window):
        tutorial_window.setObjectName("tutorial_window")
        tutorial_window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(tutorial_window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tutorial_label = QtWidgets.QLabel(self.centralwidget)
        self.tutorial_label.setText("")
        self.tutorial_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tutorial_label.setObjectName("tutorial_label")
        self.verticalLayout.addWidget(self.tutorial_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        tutorial_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tutorial_window)
        self.statusbar.setObjectName("statusbar")
        tutorial_window.setStatusBar(self.statusbar)

        self.retranslateUi(tutorial_window)
        QtCore.QMetaObject.connectSlotsByName(tutorial_window)

    def retranslateUi(self, tutorial_window):
        _translate = QtCore.QCoreApplication.translate
        tutorial_window.setWindowTitle(_translate("tutorial_window", "Tutorial"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tutorial_window = QtWidgets.QMainWindow()
    ui = Ui_tutorial_window()
    ui.setupUi(tutorial_window)
    tutorial_window.show()
    sys.exit(app.exec_())
